"use client";
import Link from "next/link";
import { useState } from "react";
import { ArrowUpRight, Camera, Menu, MessageCircle, X } from "lucide-react";
const links = [["Produtos","/produtos"],["Experiência SPA","/experiencia"],["Curso Vela Gruta","/curso"],["Sobre","/sobre"],["Contato","/contato"]];
export function Header(){const[open,setOpen]=useState(false);return <header className="site-header"><Link href="/" className="brand" aria-label="DH SpaH — início"><img src="/logo.png" alt=""/><span><b>DH</b> SpaH<small>Aromas & bem-estar</small></span></Link><nav className="desktop-nav" aria-label="Navegação principal">{links.map(([label,href])=><Link key={href} href={href}>{label}</Link>)}</nav><a className="header-cta" href="https://wa.me/5512991382620?text=Olá%20DH%20SpaH!%20Gostaria%20de%20saber%20mais." target="_blank" rel="noreferrer">Falar com a DH <ArrowUpRight size={16}/></a><button className="menu-button" onClick={()=>setOpen(!open)} aria-label="Abrir menu" aria-expanded={open}>{open?<X/>:<Menu/>}</button>{open&&<div className="mobile-menu">{links.map(([label,href])=><Link onClick={()=>setOpen(false)} key={href} href={href}>{label}</Link>)}<a href="https://wa.me/5512991382620" target="_blank" rel="noreferrer">Chamar no WhatsApp</a></div>}</header>}
export function Footer(){return <footer className="footer"><div className="footer-mark"><img src="/logo.png" alt="DH SpaH"/><p>Pequenos rituais.<br/>Grandes respiros.</p></div><div><span>EXPLORE</span><Link href="/produtos">Produtos</Link><Link href="/experiencia">Experiência SPA</Link><Link href="/curso">Curso</Link></div><div><span>CONVERSE</span><a href="https://instagram.com/dhspah" target="_blank" rel="noreferrer"><Camera size={15}/> @dhspah</a><a href="https://wa.me/5512991382620" target="_blank" rel="noreferrer"><MessageCircle size={15}/> WhatsApp</a></div><div className="footer-bottom">© 2026 DH SpaH <i/> Beleza · qualidade · sofisticação</div></footer>}
export function WhatsApp(){return <a className="whatsapp" href="https://wa.me/5512991382620?text=Olá%20DH%20SpaH!" target="_blank" rel="noreferrer" aria-label="Conversar pelo WhatsApp"><MessageCircle/></a>}
export function Shell({children}:{children:React.ReactNode}){return <><Header/>{children}<Footer/><WhatsApp/></>}
export function PageHero({eyebrow,title,text,image}:{eyebrow:string,title:string,text:string,image?:string}){return <section className="page-hero"><div className="page-hero-copy"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{text}</p></div>{image&&<div className="page-hero-image"><img src={image} alt=""/></div>}</section>}
